# Generated by Django 5.0.3 on 2024-05-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employee_obj',
            new_name='employee_object',
        ),
    ]
