# Generated by Django 5.0.4 on 2024-05-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lullaby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_object',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lullaby.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_object',
            field=models.ManyToManyField(blank=True, to='lullaby.size'),
        ),
    ]
