# Generated by Django 5.0.3 on 2024-07-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('salary', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
